### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by jeanleonino** [yiom/sketchpad#12] opened 2016-03-31 16:17 UTC

**Comment by Nikitaw99** [comment] 2016-04-01 19:15
What linter?

**Comment by nihey** [comment] 2016-04-01 20:13
@Nikitaw99 Probably [eslint](https://github.com/eslint/eslint) or [jshint](https://github.com/jshint/jshint). I've used both and they're very good

**Comment by Nikitaw99** [comment] 2016-04-04 16:27
@nihey Thanks for pointing it out! I honestly like jshint ;)

**Comment by nihey** [comment] 2016-04-26 00:51
Duplicate of https://github.com/yiom/sketchpad/issues/3

**Closed by nihey** 2016-04-26 00:51 UTC
Labels: duplicate, enhancement
